services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DATABASE_ROOT_NAME}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: "${DATABASE_ROOT_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DATABASE_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DATABASE_ROOT_PASSWORD}"
    depends_on:
      - mongo

volumes:
  mongo_data:
